### ISSUE TITLE
[SUGGESTION] Art assets

### ISSUE THREAD

**Issue by sola-ezili** [jfemory/goActionAdventure#2]
Art assets are one of the most important things in a game, but while prototyping and getting the engine built, it may be a more efficient use of time to use solid-color tiles to represent various map tiles. No need to spend hours perfecting a water tile or door tile when you can just use solid blue, brown, etc. placeholders that our brains associate with those things. The polishing comes later.

**Comment by jfemory** [comment]
I snagged a simple tileset to try. I'm not making art assets, myself, either. I don't think I am, at least. I should have someone lined up. Thanks. I will take that suggestion, directly, though, and spec out maps based on solid tiles.
