### ISSUE TITLE
[RFC] Milestones

### ISSUE THREAD

**Issue by sola-ezili** [jfemory/goActionAdventure#3]
### Request for comments.
Going off the current to-do list, I feel like there are logical milestone groupings to benefit from. I would consider these all alpha version milestones leading up to a beta version.

1. **Map engine** (world/map/chunk loading, etc.)
2. **Camera and Sprites** (camera and sprite handling)
3. **Actors** (players, enemies, AI)
4. **Inventories** (player inventories, chests, drops, etc.)
5. **Animation engine**

**Comment by jfemory** [comment]
New commit should address the roadmap.
